package com.meditrack.app.presentation.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF1A5EBE)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD6E3FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001B3F)
val md_theme_light_secondary = Color(0xFF22875A)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFA8F5C8)
val md_theme_light_onSecondaryContainer = Color(0xFF00210F)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF9F9FF)
val md_theme_light_onBackground = Color(0xFF191C20)
val md_theme_light_surface = Color(0xFFF9F9FF)
val md_theme_light_onSurface = Color(0xFF191C20)
val md_theme_light_surfaceVariant = Color(0xFFE0E2EC)
val md_theme_light_onSurfaceVariant = Color(0xFF44474E)
val md_theme_light_outline = Color(0xFF74777F)
val md_theme_light_inverseOnSurface = Color(0xFFF1F0F4)
val md_theme_light_inverseSurface = Color(0xFF2E3036)
val md_theme_light_inversePrimary = Color(0xFFA9C7FF)

val md_theme_dark_primary = Color(0xFFA9C7FF)
val md_theme_dark_onPrimary = Color(0xFF003063)
val md_theme_dark_primaryContainer = Color(0xFF00468C)
val md_theme_dark_onPrimaryContainer = Color(0xFFD6E3FF)
val md_theme_dark_secondary = Color(0xFF8CD8AD)
val md_theme_dark_onSecondary = Color(0xFF00391E)
val md_theme_dark_secondaryContainer = Color(0xFF005231)
val md_theme_dark_onSecondaryContainer = Color(0xFFA8F5C8)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF0B0F19)
val md_theme_dark_onBackground = Color(0xFFE2E2E9)
val md_theme_dark_surface = Color(0xFF0B0F19)
val md_theme_dark_onSurface = Color(0xFFE2E2E9)
val md_theme_dark_surfaceVariant = Color(0xFF44474E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC4C6D0)
val md_theme_dark_outline = Color(0xFF8E9099)
val md_theme_dark_inverseOnSurface = Color(0xFF191C20)
val md_theme_dark_inverseSurface = Color(0xFFE2E2E9)
val md_theme_dark_inversePrimary = Color(0xFF1A5EBE)

// Glassmorphism and Custom Semantic Colors for rich aesthetics
val GlassWhiteLight = Color(0xFFFFFFFF).copy(alpha = 0.85f)
val GlassWhiteDark = Color(0xFF1A1F2D).copy(alpha = 0.85f)
val GlassBorderLight = Color(0xFFFFFFFF).copy(alpha = 0.5f)
val GlassBorderDark = Color(0xFFFFFFFF).copy(alpha = 0.1f)
val GradientPrimaryStart = Color(0xFF3B82F6)
val GradientPrimaryEnd = Color(0xFF06B6D4)
val GradientSurfaceStart = Color(0xFF1E293B)
val GradientSurfaceEnd = Color(0xFF0F172A)
